### ISSUE TITLE
when using docker-compose, occurs a error, could you please upload your docker-compose project.

### ISSUE THREAD

**Issue by shougao** [yorkwu1977/jhi-example-appstack#1]
get the application work very good locally.
docker all application and using mvn -Pdev clean package jib:dockerBuild, follow the link, "https://www.cnblogs.com/yorkwu/p/9336251.html" , when the registry center display gateway, uaa, microservice1 are all down. log show "when using docker-compose, occurs a error, could you please upload your docker-compose project."
could you please figure out my mistake or share your docker-compose project.
thank you very much, look forward to your reply.

**Comment by shougao** [comment]
sent a qq email to you. 
look forward to your reply

**Comment by yorkwu1977** [comment]
jhipster v5.4.0的版本中，默认docker打包插件变更为jib:dockerBuild。我写这篇博客时的版本应该还是v5.1.0。所以，要不你用jhipster:v5.4.0以下的版本来docker build。要不把工程updfate到新的版本，然后用jib:dockerBuild来打包，但升级之后能否正常，我没试过，祝你好运：）
